### PR TITLE
Refactoring / Code cleanup

### PR DESCRIPTION
**Pull request by jkraemer**
Hi,

I just did a few improvements for setting up your plugin for a customer at Planio:

- removed the database migration, for user preferences there is already the UserPreference class which offers a generic way to store such values without a schema change. This also made the controller patch obsolete.
- cleaned up the issues helper patch
- cleaned up the view code by moving the big chunk of Javascript into the external JS file

Please have a look and let me know what you think :)

Cheers,
Jens

### CODE REVIEW

**Comment by GEROMAX** [comment]
Hi @jkraemer .

Thank you for refactoring.
I think that it is a good coding policy.

I will try to incorporate it, with a bug fix.
And testing in my environment.

Thanks.

**Comment by GEROMAX** [comment]
Hi @jkraemer .

I tested your 'PR' in my environment.
But it will not work.

I think that, no need cleanup for issues helper.
because haven't controller on my plugin.
(since there is no unique view)

Please tell me.
Will not work in 'Planio' without 'clean issues helper' must?

**Comment by jkraemer** [comment]
It works for me in an otherwise plain Redmine (trunk). What error do you get?

Why do you first define the methods named `def_something` only to later alias them to their final names? I have never seen this pattern anywhere before and do not think it does any good...

**Comment by GEROMAX** [comment]
Hi,

This error occur.(3.3.3.stable)

`ActionView::Template::Error (undefined method `has_grandson_issues?' for #<#<Class:0x4136aa8>:0x40ed7a0>):
    1: <% if has_grandson_issues?(@issue) %>
    2:   <%= content_for :header_tags do
    3:     stylesheet_link_tag("subtask_list_accordion", :plugin => "redmine_subtask_list_accordion") +
    4:     javascript_include_tag("subtask_list_accordion", :plugin => "redmine_subtask_list_accordion")
  plugins/redmine_subtask_list_accordion/app/views/issues/_subtask_list_accordion_partial.html.erb:1:in `_plugins_redmine_subtask_list_accordion_app_views_issues__subtask_list_accordion_partial_html_erb___958528632_78117948'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/show.html.erb:92:in `_app_views_issues_show_html_erb___10734698_33961152'
  app/controllers/issues_controller.rb:122:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:119:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'`


Oh. my English is poor... orz.
I don't know 'def_something' method.

Reason of patching for 'issues_helper', Because I want to call original method(has_grandson_issues?) from the view of 'issues'.
(PR code was [has_grandson_issues?]  out of scope  in my environment)

Sorry, I'm more focus about working than to good or bad, in this plugin.
Off course, I think so good your policy basically.

**Comment by jkraemer** [comment]
hello, please checkout the last commit in the other pull request I just created (dont know why github did not just append this here...) - https://github.com/GEROMAX/redmine_subtask_list_accordion/pull/7/commits/179b9b3fa815280d8bc8e1a75a7b81d4ff878793

There I remove the issues helper patch completely since these two methods do not really have to be mixed in there. This should solve your problem.

**Comment by GEROMAX** [comment]
Wow, that's strange!
Okay.. I watch carefully and try again that.

I appreciate new PR.

**Pull request merged**
